server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://39.106.38.77:3306/yaouguoji?useSSL=false
    username: yaouguoji
    password: liuwen
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    default-domain: platform
  redis:
    database: 0
    host: 47.92.154.234
    port: 6379
    password: yaouguoji

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: com.yaouguoji.platform.entity
